#!/usr/bin/env bash

if [$# != 4]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	echo "ssh -i path_to_k -o StrictHostKeyChecking=no ${IP}"
	echo "scp -i path_to_k -o StrictHostKeyChecking=no source${IP} ${dest}:~/"
	echo "scp file ${usrn}:~/"
fi
