#!/usr/bin/env bash
# Script for transferring a file to a server
if [ $# != 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else	
	sudo scp -i $4 -o StrictHostKeyChecking=no $1 "$3"@"$2" 
	ssh $3@$2 "ls ~/"
fi
