#!/usr/bin/env bash
# Script for transferring a file to a server
if [ $# != 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else	
	#echo "ssh -i path_to_k -o StrictHostKeyChecking=no ${IP}"
	echo "scp -i $4 $1 -o StrictHostKeyChecking=no $2 $3:~/"
fi
