#!/usr/bin/env bash
# Script to configure Nginx
sudo apt update; sudo apt upgrade -y;
sudo apt install -y nginx;
# echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_d.html 

sudo sed -i '/listen [::]:80 default_server ipv6only=on;/a  
server_name /redirect_me;
rewrite ^/$ https://www.digitalocean./$1 permanent;
' /etc/nginx/sites-enabled/default;

sudo service nginx restart;
