#!/usr/bin/env bash
# Script for configuring nginx load balancer
h_name=$(hostname -a)

# sudo sed '/^server {/a add_header X-server-by ${h_name}' 
sudo apt update; sudo apt upgrade -y;
sudo apt install nginx -y;

{
	echo -e "server {\n\t"
	echo -e "listen 80 default_server;\n\t"
	echo -e "listen [::]:80 default_server;\n\t";
	
	echo -e "add_header X-Served-By \"$h_name\";\n\t";

	echo -e "root /var/www/html\n\t;";

	echo -e "index index.html index.htm index.nginx-debian.html;\n\t";

	echo -e "server_name _\n\t;";

	echo -e "location / {\n\t"
	echo -e "	try_files \$uri \$uri/ =404;\t\n";
	echo -e"\t}"
	echo "}"
} | sudo tee /etc/nginx/nginx.conf;
sudo service nginx reload;
