#!/usr/bin/env bash
# Script for configuring nginx load balancer
h_name=$(hostname -b)
sudo sed '/^server {/a add_header X-server-by ${h_name}' /etc/nginx/site-enabled/default
# sed -i '/pattern/d' file
