#!/usr/bin/env bash
# Script to install nginx
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0
apt get install haproxy=2.0.\*
echo "backend\n\tserver " | sudo tee /etc/haproxy/haproxy.cnf
exit
