#!/usr/bin/env bash
# script to enable connection on port 80
sudo ufw allow "nginx http";
sudo ufw reload 

file_cont="worker_processes  1;
events {
  worker_connections  1024;
}    
http{
  upstream back-stream {
    server back:8080;
  }
  server {
    listen 80;
    listen [::]:80;
    server_name test.com www.test.com;
    location / {
      root   /usr/share/nginx/html;
      resolver 121.0.0.11;
      proxy_pass http://back-stream;
    }
  }
} ";
echo "$file_cont" | sudo tee /etc/nginx/nginx.conf
sudo service nginx start;
