#!/usr/bin/env bash
# Creates a script in /var/run/


file=/var/run/myscript.pid
su touch "$file"
echo $$ >> $file

trap 'echo Y U no love me?! ' SIGTERM
trap 'echo I hate the kill command; su rm "$file"; exit' SIGTERM
trap 'su rm "$file"; exit' SIGQUIT

while true
do
	echo To infinity and beyond
	sleep 2
done
