#!/usr/bin/env bash
# Creates a script in /var/run/


file=/var/run/myscript.pid
su touch "$file"
echo $$ >> $file

trap 'echo 'SIGTERM;
[SIGINT]; 
	echo Y U no love me?!

[SIGTERM | SIGQUIT];
	su rm file
	break
while true
do
	echo To infinity and beyond
done
