#!/usr/bin/env bash
# This script loops from 1 to 10 and display messages if at 4th and 8th num

w=1
while [ "$w" -le 10 ]
do
	if [ "$w" -eq 4 ]; then
		printf "bad luck\n"
	elif [ "$w" -eq 8 ]; then
		printf "good luck\n"
	else
		echo Best School
	fi
	w=$((w + 1))
done

