#!/usr/bin/env bash
# This script loops from 1 to 10 and display messages if at 4th and 8th num

w=1
while [ "$w" -le 20 ]
do
	if [ "$w" -eq 4 ]; then
		echo $w
		printf "bad luck from China\n"
	elif [ "$w" -eq 9 ]; then
		echo $w
		printf "bad luck from Japan\n"
	elif [ "$w" -eq 17 ]; then
		echo $w
		printf "bad luck from Italy\n"
	else
		echo $w
	fi
	w=$((w + 1))
done

