#!/usr/bin/env bash
# This script loops from 1 to 10 and display messages if at 4th and 8th num

w=1
while [ "$w" -le 20 ]
do
	echo $w
	case "$w" in 
	4)
		echo "bad luck from China";;
	9)
		echo "bad luck from Japan";;
	17)
		echo "bad luck from Italy";;
esac
	w=$((w + 1))
done

