#!/usr/bin/env bash
# This script count time in hour from 0 to 24
hour=0
min=1
echo Hour: $hour
while [ "$hour" -lt 12 ]
do
	hour=$((hour + 1))
	while [ "$min" -le 60 ]
	do
		if [ "$min" -eq 60 ]; then
			echo Hour: $hour
		else
			echo $min
		fi
		min=$((min + 1))
	done
	min=1
done
