#!/usr/bin/env bash
# Script for printing info about a file

file="$@"

if [ -e "$file" ]
then
	if [ -!s ]
	then
		echo $file file is empty
	fi
	if [ -s "$file" ]
	then
		echo $file is not empty
	fi
	if [ -f "$file" ]
	then
		echo $file is regular file
	fi

else
	echo $file file does not exist
fi

