#!/usr/bin/env bash
# Script for printing info about a file

file="$1"

if [ -e "$file" ]
then
	if [ -s "$file" ]
	then
		echo "$file" is not empty
	else
		echo "$file" file is empty
	fi

	if [ -f "$file" ]
	then
		echo "$file" is regular file
	fi

else
	echo "$file" file does not exist
fi
