#!/usr/bin/env bash
# Script to configure an Ubuntu server
sudo cp /etc/hosts /etc/hosts.old
sudo cp /etc/hosts ~/hosts.new

sudo sed 's/localhost	127.0.0.1/localhost	127.0.0.2/' /etc/hosts
echo "facebook	8.8.8.8" | sudo tee -a /etc/hosts > /dev/null
#sudo echo "$(cat ~/host.new)" > /etc/hosts
