#!/usr/bin/env bash
# Script to configure an Ubuntu server
sudo cp /etc/hosts /etc/hosts.old
sudo cp /etc/hosts ~/hosts.new

echo "localhost	127.0.0.2" >> ~/hosts.new
echo "facebook	8.8.8.8" >> ~/hosts.new
sudo echo "$(cat ~/host.new)" > /etc/hosts
